<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetCore.CAP" Version="8.0.0" />
    <PackageReference Include="MediatR" Version="12.2.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Qf.Core.AutoMapper" Version="3.0.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Qf.SysTodoList.Domain\Qf.SysTodoList.Domain.csproj" />
    <ProjectReference Include="..\Qf.SysTodoList.Infrastructure\Qf.SysTodoList.Infrastructure.csproj" />
  </ItemGroup>

</Project>
